services:
  mongo:
    image: mongo@sha256:acc73edf60b63fd8e3752e8b40b5304d35e87743ecbe8dc63ae6145ebbadc7b5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./people.json.gz
        target: /mnt/datafiles/people.json.gz
      - type: bind
        source: ./init.sh
        target: /docker-entrypoint-initdb.d/init.sh

